<footer>
        <div class="footer-top">
           
            <div class="logo-footer">
                <img src="images/logo/logover1.svg" alt="DropFresh logo">
                <p>At DropFresh, we're passionate about sustainability and protecting the environment. Learnmore about
                    our eco-friendly practices and our dedication to minimizing our environmental footprint for a
                    healthier planet</p>
            </div>
        </div>

        <div class="footer-hr"></div>

        <div class="footer-middle">
            <h3>Contact Information</h3>
            <ul>
                <li class="lh">Email: <a href="mailto:104977535@student.swin.edu.au">104977535@student.swin.edu.au</a>
                </li>
                <li class="lh">Phone: 0849026110</li>
                <li class="lh">Address: A35, Bach Dang, Tan Binh District, Ho Chi Minh City </li>
            </ul>
            <h4><a href="index.html">Terms of Use | Privacy Policy</a></h4>
        </div>

        <div class="footer-hr"></div>
        <div class="footer-bottom">
            <h5>&copy; 2024 DropFresh</h5>
        </div>
    </footer>
</body>

</html>