<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="description" content="Assignment Part 1 - Home Page">
    <meta name="author" content="Dong Nhi Truong">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="styles/style.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Oleo+Script:wght@400;700&display=swap" rel="stylesheet">
    <link rel="icon" href="images/logo/favicon.svg">
    <title>DropFresh - Home Page</title>
<style>
    
</style>


</head>

<body>
    <header>
        <div class="contact">
                <div><a class="btn" href="index.php?pg=enhancement">Enhancement Assignment 1</a></div>
               <div> <a class="btn" href="index.php?pg=enhancement2">Enhancement Assignment 2</a></div>
            <ul>
                <li id="hotline"><i class="fa-solid fa-phone icon" ></i> &nbsp;Hotline
                    <span><strong>0849026110</strong></span>
                </li>
                <li id="mail"><i class="fa-solid fa-envelope icon" ></i><a
                        href="mailto:104977535@student.swin.edu.au">&nbsp;Contact Us</a></li>
            </ul>
        </div>
        <!-- desktop menubar -->
        <div class="menu"> 
            <div class="logo">
                <a href="#menu-bar" class="tmenu"><i class="fa-solid fa-bars"></i>menu</a>
                <a href="#" class="tlogo"><img src="images/logo/logover1.svg" alt="DropFresh logo"></a></div>
            <div class="menu-wrapper">
                <nav class="info1">
                    <ul>
                        <li class="menubar"><a href="index.php"><i class="fa-solid fa-house"></i>&nbsp;Home Page</a></li>
                        <li class="menubar"><a href="index.php?pg=jobs">Career Opportunities</a></li>
                        <li class="menubar"><a href="index.php?pg=apply">Job Application</a></li>
                        <li class="menubar"><a href="index.php?pg=about">About Us</a></li>
                    </ul>
                </nav>
            </div>
        </div>
        <!-- mobile responsive menubar -->
        <nav class="info" id="menu-bar">
            <ul>
                <li class="menubar"><a href="index.php"><i class="fa-solid fa-house"></i>&nbsp;Home Page</a></li>
                <li class="menubar"><a href="index.php?pg=jobs">Career Opportunities</a></li>
                <li class="menubar"><a href="apply.html">Job Application</a></li>
                <li class="menubar"><a href="index.php?pg=about">About Us</a></li>
            </ul>
        </nav>
    </header>