
<div class="herosizeindex">
    <div class="hero">
    </div>
   </div>
    <article>    
        <h1><strong>Welcome to DropFresh - Pure Refreshment, Every Drop Counts!</strong></h1>
        <section class="homepage-section1">
            <div class="section-title">
                <div class="title-hr"></div>
                <h2>Discover Our Promise of Purity</h2>
                <div class="title-hr"></div>
            </div>
            <div class="homepage-section1-body">
                <div class="st1 box">
                    <h3>Refreshing Taste, Pure Source:</h3>
                    <p>DropFresh mineral water comes from pure springs located in untouched natural environments. The
                        water goes through thorough filtration processes to ensure that it maintains its natural
                        minerals and refreshing flavor.</p>
                </div>
                
                <div class="nd2 box">
                    <h3>Purity You Can Trust:</h3>
                    <p>We recognize the significance of being transparent about the water you consume. That is why we
                        offer full traceability for our water, enabling you to know its origin and the treatment process
                        it undergoes at each stage.</p>
                </div>

                <div class="rd3 box">
                    <h3>Sustainable Development:</h3>
                    <p>DropFresh is committed to protecting the environment by using eco-friendly packaging and sourcing
                        products ethically. Our goal is to protect the planet for future generations while providing the
                        cleanest water.</p>
                </div>
                
            </div>
        </section>
            
            <div class="section2">
                <h2>Experience the DropFresh Difference</h2>
                <img class="largesection2 rela" src="images/section2_background.svg" alt="Largesection">
                <img class="largesection2 abso1" src="images/mascot/1st_mascot_section2.svg" alt="Largesection1">
                <img class="largesection2 abso2" src="images/mascot/2nd_mascot_section2.svg" alt="Largesection2">
    
                <img class="responsivesection2" src="images/mascot/responsive_1st_mascot_section2.svg"
                    alt="Responsivesection1">
                <img class="responsivesection2" src="images/mascot/responsive_2nd_mascot_section2.svg"
                    alt="Responsivesection2">
            </div>
         <div class="footer-top1">
                <div class="join">
                    <h2>Become a member of the DropFresh family</h2>
                    <div class="button" id="hover">Join "Stay hydrated" community</div>
                </div>

                <div class="follow">
                    <h2>Follow us</h2>
                    <ul>
                        <li id="facebook"><a href="https://www.facebook.com/swinburneuniversityoftechnology"><i class="fa-brands fa-facebook fa-2xl">Facebook</i></a>
                        </li>
                        <li id="youtube"><a href="https://youtu.be/m94GFYza_l0"><i class="fa-brands fa-youtube fa-2xl">Youtube</i></a>
                        </li>
                    </ul>
                </div>
            </div>
    </article>
 
    